%Creates a dictionary of FRC configurations.
%   The dictionary maps a tag to a configuration specified in terms of subcarrier
%   spacing, PRB set, target code rate and modulation.

%   Copyright 2021-2025 Software Radio Systems Limited
%
%   This file is part of srsRAN-matlab.
%
%   srsRAN-matlab is free software: you can redistribute it and/or
%   modify it under the terms of the BSD 2-Clause License.
%
%   srsRAN-matlab is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
%   BSD 2-Clause License for more details.
%
%   A copy of the BSD 2-Clause License can be found in the LICENSE
%   file in the top-level directory of this distribution.

function frcdictionary = createFRC()
    frcdictionary = dictionary( ...
... Table A.3-2: FRC parameters for FR1 PUSCH performance requirements,
... transform precoding disabled, Additional DM-RS position = pos1 and
... one transmission layer (QPSK, R=193/1024).
        'G-FR1-A3-8',  struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:24, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-9',  struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:51, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-10', struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:105, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-11', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:23, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-12', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:50, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-13', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:105, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-14', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:272, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
... Table A.3-4: FRC parameters for FR1 PUSCH performance requirements,
... transform precoding disabled, Additional DM-RS position = pos1 and
... two transmission layers (QPSK, R=193/1024).
        'G-FR1-A3-22', struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:24, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-23', struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:51, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-24', struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:105, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-25', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:23, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-26', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:50, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-27', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:105, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-28', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:272, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
... Table A.3-6: FRC parameters for FR1 PUSCH performance requirements,
... transform precoding enabled, Additional DM-RS position = pos1 and
... one transmission layer (QPSK, R=193/1024).
        'G-FR1-A3-31', struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:24, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-32', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:23, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
... Table A.3-16: FRC parameters for FR1 PUSCH performance requirements,
... transform precoding disabled, Additional DM-RS position = pos1 and
... four transmission layers (QPSK, R=193/1024).
        'G-FR1-A3-39', struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:24, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-41', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:23, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-42', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:272, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
... Table A.4-2: FRC parameters for FR1 PUSCH performance requirements,
... transform precoding disabled, Additional DM-RS position = pos1 and
... one transmission layer (16QAM, R=658/1024).
        'G-FR1-A4-8',  struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:24, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A4-9',  struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:51, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A4-10', struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:105, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A4-11', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:23, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A4-12', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:50, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A4-13', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:105, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A4-14', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:272, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
... Table A.4-4: FRC parameters for FR1 PUSCH performance requirements,
... transform precoding disabled, Additional DM-RS position = pos1 and
... two transmission layers (16QAM, R=658/1024)
        'G-FR1-A4-22', struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:24, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A4-23', struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:51, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A4-24', struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:105, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A4-25', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:23, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A4-26', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:50, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A4-27', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:105, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A4-28', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:272, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
... Table A.5-2: FRC parameters for FR1 PUSCH performance requirements,
... transform precoding disabled, Additional DM-RS position = pos1 and
... one transmission layer (64QAM, R=567/1024)
        'G-FR1-A5-8',  struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:24, ...
                              'TargetCodeRate',    567/1024, ...
                              'Modulation',        '64QAM'), ...
        'G-FR1-A5-9',  struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:51, ...
                              'TargetCodeRate',    567/1024, ...
                              'Modulation',        '64QAM'), ...
        'G-FR1-A5-10', struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:105, ...
                              'TargetCodeRate',    567/1024, ...
                              'Modulation',        '64QAM'), ...
        'G-FR1-A5-11', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:23, ...
                              'TargetCodeRate',    567/1024, ...
                              'Modulation',        '64QAM'), ...
        'G-FR1-A5-12', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:50, ...
                              'TargetCodeRate',    567/1024, ...
                              'Modulation',        '64QAM'), ...
        'G-FR1-A5-13', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:105, ...
                              'TargetCodeRate',    567/1024, ...
                              'Modulation',        '64QAM'), ...
        'G-FR1-A5-14', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:272, ...
                              'TargetCodeRate',    567/1024, ...
                              'Modulation',        '64QAM'), ...
... Table A.7-4: FRC parameters for FR1 PUSCH performance requirements,
... transform precoding disabled, Additional DM-RS position = pos1 and
... four transmission layers (16QAM, R=434/1024).
        'G-FR1-A7-1',  struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:24, ...
                              'TargetCodeRate',    434/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A7-3',  struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:23, ...
                              'TargetCodeRate',    434/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A7-4',  struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:272, ...
                              'TargetCodeRate',    434/1024, ...
                              'Modulation',        '16QAM'), ...
... Custom FRC configurations.
        'Custom-Max-1PRB', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0, ...
                              'TargetCodeRate',    772/1024, ...
                              'Modulation',        '256QAM'), ...
        'Custom-Max-2PRB', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:1, ...
                              'TargetCodeRate',    772/1024, ...
                              'Modulation',        '256QAM'), ...
        'Custom-Max-4PRB', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:3, ...
                              'TargetCodeRate',    772/1024, ...
                              'Modulation',        '256QAM'), ...
        'Custom-Max-8PRB', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:7, ...
                              'TargetCodeRate',    772/1024, ...
                              'Modulation',        '256QAM'), ...
        'Custom-Max-15PRB', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:14, ...
                              'TargetCodeRate',    772/1024, ...
                              'Modulation',        '256QAM'), ...
        'Custom-Max-10MHz', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:23, ...
                              'TargetCodeRate',    772/1024, ...
                              'Modulation',        '256QAM'), ...
        'Custom-Max-20MHz', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:50, ...
                              'TargetCodeRate',    772/1024, ...
                              'Modulation',        '256QAM'), ...
        'Custom-Max-40MHz', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:105, ...
                              'TargetCodeRate',    772/1024, ...
                              'Modulation',        '256QAM'), ...
        'Custom-Max-100MHz', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:272, ...
                              'TargetCodeRate',    772/1024, ...
                              'Modulation',        '256QAM') ...
    );
end % of function frcdictionary = createFRC()
