%Creates test configurations for PUSCH, Type A, 100 MHz channel bandwidth, 30 kHz SCS.
%   These test cases are specified in TS38.104 V15.19.0, Table 8.2.1.2-7.

%   Copyright 2021-2025 Software Radio Systems Limited
%
%   This file is part of srsRAN-matlab.
%
%   srsRAN-matlab is free software: you can redistribute it and/or
%   modify it under the terms of the BSD 2-Clause License.
%
%   srsRAN-matlab is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
%   BSD 2-Clause License for more details.
%
%   A copy of the BSD 2-Clause License can be found in the LICENSE
%   file in the top-level directory of this distribution.

function testConfig = createTestConfigTable8_2_1_2_7()
    testConfig = { ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-7 Row 1', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A3-14', ...
            'SNR',                 -2.8 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-7 Row 2', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A4-14', ...
            'SNR',                 10.2 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-7 Row 3', ...
            'DelayProfile',        'TDLA30', ...
            'MaximumDopplerShift', 10, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A5-14', ...
            'SNR',                 13 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-7 Row 4', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A3-14', ...
            'SNR',                 -5.8 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-7 Row 5', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A4-14', ...
            'SNR',                 6.5 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-7 Row 6', ...
            'DelayProfile',        'TDLA30', ...
            'MaximumDopplerShift', 10, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A5-14', ...
            'SNR',                 9 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-7 Row 10', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             2, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A3-28', ...
            'SNR',                 1.4 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-7 Row 11', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NTxAnts',             2, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A4-28', ...
            'SNR',                 19.2 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-7 Row 12', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             2, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A3-28', ...
            'SNR',                 -2.2 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-7 Row 13', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NTxAnts',             2, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A4-28', ...
            'SNR',                 11.6 ...
        ), ...
    };
end % of function TestConfig = createTestConfigTable8_2_1_2_7()
