%Creates test configurations for PUSCH, Type A, 20 MHz channel bandwidth, 15 kHz SCS.
%   These test cases are specified in TS38.104 V15.19.0, Table 8.2.1.2-3.

%   Copyright 2021-2025 Software Radio Systems Limited
%
%   This file is part of srsRAN-matlab.
%
%   srsRAN-matlab is free software: you can redistribute it and/or
%   modify it under the terms of the BSD 2-Clause License.
%
%   srsRAN-matlab is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
%   BSD 2-Clause License for more details.
%
%   A copy of the BSD 2-Clause License can be found in the LICENSE
%   file in the top-level directory of this distribution.

function testConfig = createTestConfigTable8_2_1_2_3()
    testConfig = { ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-3 Row 1', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A3-10', ...
            'SNR',                 -2.1 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-3 Row 2', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A4-10', ...
            'SNR',                 10.0 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-3 Row 3', ...
            'DelayProfile',        'TDLA30', ...
            'MaximumDopplerShift', 10, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A5-10', ...
            'SNR',                 12.4 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-3 Row 4', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A3-10', ...
            'SNR',                 -5.5 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-3 Row 5', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A4-10', ...
            'SNR',                 6.2 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-3 Row 6', ...
            'DelayProfile',        'TDLA30', ...
            'MaximumDopplerShift', 10, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A5-10', ...
            'SNR',                 8.6 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-3 Row 10', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             2, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A3-24', ...
            'SNR',                 2.1 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-3 Row 11', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NTxAnts',             2, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A4-24', ...
            'SNR',                 18.3 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-3 Row 12', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             2, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A3-24', ...
            'SNR',                 -1.8 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-3 Row 13', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NTxAnts',             2, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A4-24', ...
            'SNR',                 11.1 ...
        ), ...
    };
end % of function TestConfig = createTestConfigTable8_2_1_2_3()
