%Creates test configurations for PUSCH, Type A, transform precoding enabled.
%   These test cases are specified in TS38.104 V15.19.0, Table 8.2.2.2-x.

%   Copyright 2021-2025 Software Radio Systems Limited
%
%   This file is part of srsRAN-matlab.
%
%   srsRAN-matlab is free software: you can redistribute it and/or
%   modify it under the terms of the BSD 2-Clause License.
%
%   srsRAN-matlab is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
%   BSD 2-Clause License for more details.
%
%   A copy of the BSD 2-Clause License can be found in the LICENSE
%   file in the top-level directory of this distribution.

function testConfig = createTestConfigTable8_2_2_2_x()
    testConfig = {
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.2.2-1 Row 1', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A3-31', ...
            'SNR',                 -2.4 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.2.2-1 Row 2', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A3-31', ...
            'SNR',                 -5.7 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.2.2-2 Row 1', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A3-32', ...
            'SNR',                 -2.5 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.2.2-2 Row 2', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A3-32', ...
            'SNR',                 -5.7 ...
        ), ...
    };
end % of function TestConfig = createTestConfigTable8_2_2_2_x()
