%Creates test configurations for PUSCH, Type A, 10 MHz channel bandwidth, 30 kHz SCS.
%   These test cases are specified in TS38.104 V15.19.0 and V19.0.0, Table 8.2.1.2-4.

%   Copyright 2021-2025 Software Radio Systems Limited
%
%   This file is part of srsRAN-matlab.
%
%   srsRAN-matlab is free software: you can redistribute it and/or
%   modify it under the terms of the BSD 2-Clause License.
%
%   srsRAN-matlab is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
%   BSD 2-Clause License for more details.
%
%   A copy of the BSD 2-Clause License can be found in the LICENSE
%   file in the top-level directory of this distribution.

function testConfig = createTestConfigTable8_2_1_2_4()
    testConfig = { ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-4 Row 1', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A3-11', ...
            'SNR',                 -2.3 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-4 Row 2', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A4-11', ...
            'SNR',                 10.2 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-4 Row 3', ...
            'DelayProfile',        'TDLA30', ...
            'MaximumDopplerShift', 10, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A5-11', ...
            'SNR',                 12.8 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-4 Row 4', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A3-11', ...
            'SNR',                 -5.6 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-4 Row 5', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A4-11', ...
            'SNR',                 6.4 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-4 Row 6', ...
            'DelayProfile',        'TDLA30', ...
            'MaximumDopplerShift', 10, ...
            'DelaySpread',         0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A5-11', ...
            'SNR',                 8.6 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-4 Row 10', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             2, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A3-25', ...
            'SNR',                 1.3 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-4 Row 11', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NTxAnts',             2, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A4-25', ...
            'SNR',                 18.4 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-4 Row 12', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             2, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A3-25', ...
            'SNR',                 -2.2 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-4 Row 13', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NTxAnts',             2, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A4-25', ...
            'SNR',                 11.2 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V19.0.0 Table 8.2.1.2-4 Row 19', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NTxAnts',             4, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A3-41', ...
            'SNR',                 1.6 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V19.0.0 Table 8.2.1.2-4 Row 20', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NTxAnts',             4, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A7-3', ...
            'SNR',                 14.9 ...
        ), ...
    };
end % of function TestConfig = createTestConfigTable8_2_1_2_4()
