%Creates test configurations for PUSCH, custom cases.
%   Simple one-tap channel and high-SNR, to combine with CFO.

%   Copyright 2021-2025 Software Radio Systems Limited
%
%   This file is part of srsRAN-matlab.
%
%   srsRAN-matlab is free software: you can redistribute it and/or
%   modify it under the terms of the BSD 2-Clause License.
%
%   srsRAN-matlab is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
%   BSD 2-Clause License for more details.
%
%   A copy of the BSD 2-Clause License can be found in the LICENSE
%   file in the top-level directory of this distribution.

function testConfig = createTestConfigCustom()
    testConfig = {
        struct( ...
            'Name',                'Custom Max 1PRB', ...
            'DelayProfile',        'single-tap', ...
            'DelaySpread',         2.0e-7, ...
            'MaximumDopplerShift', 0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             1, ...
            'FRC',                 'Custom-Max-1PRB', ...
            'SNR',                 60 ...
        ), ...
        struct( ...
            'Name',                'Custom Max 2PRB', ...
            'DelayProfile',        'single-tap', ...
            'DelaySpread',         2.0e-7, ...
            'MaximumDopplerShift', 0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             1, ...
            'FRC',                 'Custom-Max-2PRB', ...
            'SNR',                 60 ...
        ), ...
        struct( ...
            'Name',                'Custom Max 4PRB', ...
            'DelayProfile',        'single-tap', ...
            'DelaySpread',         2.0e-7, ...
            'MaximumDopplerShift', 0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             1, ...
            'FRC',                 'Custom-Max-4PRB', ...
            'SNR',                 60 ...
        ), ...
        struct( ...
            'Name',                'Custom Max 8PRB', ...
            'DelayProfile',        'single-tap', ...
            'DelaySpread',         2.0e-7, ...
            'MaximumDopplerShift', 0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             1, ...
            'FRC',                 'Custom-Max-8PRB', ...
            'SNR',                 60 ...
        ), ...
        struct( ...
            'Name',                'Custom Max 15PRB', ...
            'DelayProfile',        'single-tap', ...
            'DelaySpread',         2.0e-7, ...
            'MaximumDopplerShift', 0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             1, ...
            'FRC',                 'Custom-Max-15PRB', ...
            'SNR',                 60 ...
        ), ...
        struct( ...
            'Name',                'Custom Max 10MHz', ...
            'DelayProfile',        'single-tap', ...
            'DelaySpread',         2.0e-7, ...
            'MaximumDopplerShift', 0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             1, ...
            'FRC',                 'Custom-Max-10MHz', ...
            'SNR',                 60 ...
        ), ...
        struct( ...
            'Name',                'Custom Max 20MHz', ...
            'DelayProfile',        'single-tap', ...
            'DelaySpread',         2.0e-7, ...
            'MaximumDopplerShift', 0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             1, ...
            'FRC',                 'Custom-Max-20MHz', ...
            'SNR',                 60 ...
        ), ...
        struct( ...
            'Name',                'Custom Max 40MHz', ...
            'DelayProfile',        'single-tap', ...
            'DelaySpread',         2.0e-7, ...
            'MaximumDopplerShift', 0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             1, ...
            'FRC',                 'Custom-Max-40MHz', ...
            'SNR',                 60 ...
        ), ...
        struct( ...
            'Name',                'Custom Max 100MHz', ...
            'DelayProfile',        'single-tap', ...
            'DelaySpread',         2.0e-7, ...
            'MaximumDopplerShift', 0, ...
            'NTxAnts',             1, ...
            'NRxAnts',             1, ...
            'FRC',                 'Custom-Max-100MHz', ...
            'SNR',                 60 ...
        ) ...
    };
end % of function TestConfig = createTestConfigCustom()
