%CheckPRACHConformance Battery of conformance tests for the PRACH detector.
%   This class, based on the matlab.unittest.TestCase framework, performs a battery
%   of conformance tests on the PRACH detector. Specifically, the tests are a
%   subset of those described in TS38.104 Section 8.4 and TS38.141 Section 8.4.
%   The test consists in running a short simulation and ensuring that the estimated
%   detection and false detection probability meet the requirements.
%
%   CheckPRACHConformance Properties (TestParameter):
%
%   TestConfig  - PRACH test configuration.
%
%   CheckPRACHConformance Methods (Test, TestTags = {'conformance'})
%
%   checkPRACHdetection   - Verifies that the target detection probability is
%                           achieved for the given PRACH configuration.
%   checkPRACHfalsealarm  - Verifies that the target false detection probability
%                           is achieved for the given PRACH configuration.
%
%   Example
%      runtests('CheckPRACHConformance')
%
%   See also matlab.unittest, PRACHPERF.

%   Copyright 2021-2025 Software Radio Systems Limited
%
%   This file is part of srsRAN-matlab.
%
%   srsRAN-matlab is free software: you can redistribute it and/or
%   modify it under the terms of the BSD 2-Clause License.
%
%   srsRAN-matlab is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
%   BSD 2-Clause License for more details.
%
%   A copy of the BSD 2-Clause License can be found in the LICENSE
%   file in the top-level directory of this distribution.

classdef CheckPRACHConformance < matlab.unittest.TestCase
    properties (Constant, Hidden)
        %Folder for storing the test results in csv format.
        OutputFolder = 'conformanceResults'
        %File for storing the results in csv format.
        OutputFile = fullfile(pwd, CheckPRACHConformance.OutputFolder, ['conformancePRACH', char(datetime('now', 'Format', 'yyyyMMdd''T''HHmmss')), '.csv'])
    end % of properties (Constant, Hidden)

    properties (TestParameter)
        TestConfig = createTestConfig()
    end % of properties (TestParameter)

    methods (TestClassSetup)
        function silenceWarnings(obj)
        %Silences warnings related to non-optimized PRACH detector thresholds.
            warn = warning('query', 'srsran_matlab:srsPRACHdetector');
            warning('off', 'srsran_matlab:srsPRACHdetector');

            obj.addTeardown(@warning, warn.state, 'srsran_matlab:srsPRACHdetector');
        end

        function preparecsv(obj)
        %Creates a csv file for storing the results of all tests.

            if ~exist(obj.OutputFolder, 'dir')
                mkdir(obj.OutputFolder);
            end
            fff = fopen(obj.OutputFile, 'w');

            % Write file header.
            fprintf(fff, '#datatype measurement,tag,tag,double,dateTime:RFC3339\n');
            fprintf(fff, '#default,,,\n');
            fprintf(fff, 'm,suite,test,value,time\n');

            fclose(fff);
        end % of function preparecsv(obj)
    end % of methods (TestClassSetup)

    methods (Test, TestTags = {'conformance'})
        function checkPRACHdetection(obj, TestConfig)
        %checkPRACHdetection Verifies that the target detection probability is achieved
        %   for the given PRACH configuration.

            import matlab.unittest.fixtures.CurrentFolderFixture

            obj.applyFixture(CurrentFolderFixture('../apps/simulators/PRACHPERF'));

            pp = obj.preparePRACH(TestConfig);

            pp.TestType = 'Detection';

            nTests = 10000;
            try
                pp(TestConfig.SNR, nTests);
            catch ME
                obj.assertFail(['PRACHPER simulation failed with error: ', ME.message]);
            end

            % Export detection probability in csv format to be imported in grafana.
            writecsv(obj, TestConfig.Name, TestConfig.Format, 'detection', pp.ProbabilityDetectionPerfect);

            obj.verifyGreaterThanOrEqual(pp.ProbabilityDetectionPerfect, 0.99, ...
                'WARNING: The PRACH detection rate should not be lower than 99%.');
            obj.assertGreaterThanOrEqual(pp.ProbabilityDetectionPerfect, 0.95, ...
                'WARNING: The PRACH detection rate is below the hard acceptance threshold of 95%.');

        end % of function checkPRACHdetection(obj, TestConfig)

        function checkPRACHfalsealarm(obj, TestConfig)
        %checkPRACHfalsealarm Verifies that the target false detection probability is
        %   achieved for the given PRACH configuration.

            import matlab.unittest.fixtures.CurrentFolderFixture

            obj.applyFixture(CurrentFolderFixture('../apps/simulators/PRACHPERF'));

            pp = obj.preparePRACH(TestConfig);

            pp.TestType = 'False Alarm';

            nTests = 100000;
            try
                pp(TestConfig.SNR, nTests);
            catch ME
                obj.assertFail(['PRACHPER simulation failed with error: ', ME.message]);
            end

            % Export false-alarm probability in csv format to be imported in grafana.
            writecsv(obj, TestConfig.Name, TestConfig.Format, 'false alarm', pp.ProbabilityFalseAlarm);

            obj.verifyLessThanOrEqual(pp.ProbabilityFalseAlarm, 0.001, ...
                'WARNING: The PRACH false detection rate should not be higher than 0.1%.');
            obj.assertLessThanOrEqual(pp.ProbabilityFalseAlarm, 0.005, ...
                'WARNING: The PRACH false detection rate is above the hard acceptance threshold of 0.5%.');

        end % of function checkPRACHfalsealarm(obj, TestConfig)

    end % of methods (Test, TestTags = {'conformance'})

    methods (Access = private)
        function pp = preparePRACH(obj, TestConfig)
        %Configures a PRACHPERF object based on TestConfig and common parameter values.

            import matlab.unittest.constraints.IsFile

            try
                pp = PRACHPERF;
            catch ME
                obj.assertFail(['Could not create a PRACHPERF object because of exception: ', ...
                    ME.message]);
            end

            obj.assertClass(pp, 'PRACHPERF', 'The created object is not a PRACHPERF object.');

            obj.assertThat('../../../+srsMEX/+phy/@srsPRACHDetector/prach_detector_mex.mexa64', IsFile, ...
                'Could not find PRACH detector mex executable.');

            pp.DelayProfile = TestConfig.DelayProfile;
            if strcmp(TestConfig.DelayProfile, 'AWGN')
                pp.FrequencyOffset = 0;
            else % TDLC300
                pp.FrequencyOffset = 400;
            end % of if strcmp(TestConfig.DelayProfile, 'AWGN')

            if contains(TestConfig.Name, '8.4.2.2-1')
                pp.Format = '0';
                pp.NCS = 13;
                pp.PreambleIndex = 32;
                pp.SequenceIndex = 22;
            elseif contains(TestConfig.Name, '8.4.2.2-2')
                pp.Format = TestConfig.Format;
                pp.NCS = 23;
                pp.PUSCHSubcarrierSpacing = 15;
                pp.PreambleIndex = 0;
                pp.SequenceIndex = 0;
            else % TestConfig.Name constains 8.4.2.2-3
                pp.Format = TestConfig.Format;
                pp.NCS = 46;
                pp.PUSCHSubcarrierSpacing = 30;
                pp.PreambleIndex = 0;
                pp.SequenceIndex = 0;
            end % of if contains(TestConfig.Name, '8.4.2.2-1')

            pp.IgnoreCFO = true;
            pp.ImplementationType = 'srs';
            pp.NumReceiveAntennas = TestConfig.NRxAnts;

            pp.TimeErrorTolerance = pickTimeErrorTolerance(pp.Format, pp.DelayProfile, pp.PUSCHSubcarrierSpacing);

            pp.QuickSimulation = false;

        end % of function preparePRACH(obj, TestConfig)

        function writecsv(obj, casename, prachFormat, metric, prob)
        %Writes the test entry in the csv file.

            fff = fopen(obj.OutputFile, 'a');
            currTime = getenv("CI_PIPELINE_CREATED_AT");
            if isempty(currTime)
                currTime = char(datetime('now', 'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
            end
            fprintf(fff, '%s,matlab/PRACH conformance,%s / Format %s,%.6f,%s\n', metric, casename, prachFormat, prob, currTime);

            fclose(fff);
        end % of function writecsv(obj)
    end % of methods (Access = private)
end % of classdef CheckPRACHConformance

function tet = pickTimeErrorTolerance(prachFormat, delayProfile, scs)
% Returns the time error tolerance for the given delay profile, PRACH preamble
% format and subcarrier spacing.

    if strcmp(prachFormat, '0')
        if strcmp(delayProfile, 'AWGN')
            tet = 1.04;
        else
            tet = 2.55;
        end % of if strcmp(delayProfile, 'AWGN')
    else
        if strcmp(delayProfile, 'AWGN')
            if (scs == 15)
                tet = 0.52;
            else
                tet = 0.26;
            end % of if (scs == 15)
        else
            if (scs == 15)
                tet = 2.03;
            else
                tet = 1.77;
            end % of if (scs == 15)
        end % of if strcmp(delayProfile, 'AWGN')
    end % of if strcmp('prachFormat', '0')
end % of function pickTimeErrorTolerance(delayProfile, prachFormat, scs)

function TestConfig = createTestConfig()
% Creates a cell array of configuration structures for all the cases listed in
% the TS.

% NOTE: We comment the configurations that are not yet supported by srsRAN.

    TestConfig = { ...
        ... Long PRACH
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-1 Row 1', ...
            'DelayProfile', 'AWGN', ...
            'NRxAnts', 2, ...
            'Format', '0', ...
            'SNR', -14.5 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-1 Row 2', ...
            'DelayProfile', 'TDLC300', ...
            'NRxAnts', 2, ...
            'Format', '0', ...
            'SNR', -6.6 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-1 Row 3', ...
            'DelayProfile', 'AWGN', ...
            'NRxAnts', 4, ...
            'Format', '0', ...
            'SNR', -16.7 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-1 Row 4', ...
            'DelayProfile', 'TDLC300', ...
            'NRxAnts', 4, ...
            'Format', '0', ...
            'SNR', -11.9 ...
        ), ...
        ... Short PRACH 15 kHz
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 1', ...
            'DelayProfile', 'AWGN', ...
            'NRxAnts', 2, ...
            'Format', 'A1', ...
            'SNR', -9.3 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 1', ...
            'DelayProfile', 'AWGN', ...
            'NRxAnts', 2, ...
            'Format', 'A2', ...
            'SNR', -12.6 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 1', ...
            'DelayProfile', 'AWGN', ...
            'NRxAnts', 2, ...
            'Format', 'A3', ...
            'SNR', -14.2 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 1', ...
            'DelayProfile', 'AWGN', ...
            'NRxAnts', 2, ...
            'Format', 'B4', ...
            'SNR', -16.8 ...
        ), ...
        ... struct( ...
        ...     'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 1', ...
        ...     'DelayProfile', 'AWGN', ...
        ...     'NRxAnts', 2, ...
        ...     'Format', 'C0', ...
        ...     'SNR', -6.3 ...
        ... ), ...
        ... struct( ...
        ...     'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 1', ...
        ...     'DelayProfile', 'AWGN', ...
        ...     'NRxAnts', 2, ...
        ...     'Format', 'C2', ...
        ...     'SNR', -12.5 ...
        ... ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 2', ...
            'DelayProfile', 'TDLC300', ...
            'NRxAnts', 2, ...
            'Format', 'A1', ...
            'SNR', -2.1 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 2', ...
            'DelayProfile', 'TDLC300', ...
            'NRxAnts', 2, ...
            'Format', 'A2', ...
            'SNR', -4.8 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 2', ...
            'DelayProfile', 'TDLC300', ...
            'NRxAnts', 2, ...
            'Format', 'A3', ...
            'SNR', -6.6 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 2', ...
            'DelayProfile', 'TDLC300', ...
            'NRxAnts', 2, ...
            'Format', 'B4', ...
            'SNR', -8.8 ...
        ), ...
        ... struct( ...
        ...     'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 2', ...
        ...     'DelayProfile', 'TDLC300', ...
        ...     'NRxAnts', 2, ...
        ...     'Format', 'C0', ...
        ...     'SNR', 0.8 ...
        ... ), ...
        ... struct( ...
        ...     'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 2', ...
        ...     'DelayProfile', 'TDLC300', ...
        ...     'NRxAnts', 2, ...
        ...     'Format', 'C2', ...
        ...     'SNR', -4.9 ...
        ... ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 3', ...
            'DelayProfile', 'AWGN', ...
            'NRxAnts', 4, ...
            'Format', 'A1', ...
            'SNR', -11.6 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 3', ...
            'DelayProfile', 'AWGN', ...
            'NRxAnts', 4, ...
            'Format', 'A2', ...
            'SNR', -14.3 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 3', ...
            'DelayProfile', 'AWGN', ...
            'NRxAnts', 4, ...
            'Format', 'A3', ...
            'SNR', -16.0 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 3', ...
            'DelayProfile', 'AWGN', ...
            'NRxAnts', 4, ...
            'Format', 'B4', ...
            'SNR', -19.0 ...
        ), ...
        ... struct( ...
        ...     'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 3', ...
        ...     'DelayProfile', 'AWGN', ...
        ...     'NRxAnts', 4, ...
        ...     'Format', 'C0', ...
        ...     'SNR', -8.7 ...
        ... ), ...
        ... struct( ...
        ...     'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 3', ...
        ...     'DelayProfile', 'AWGN', ...
        ...     'NRxAnts', 4, ...
        ...     'Format', 'C2', ...
        ...     'SNR', -14.1 ...
        ... ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 4', ...
            'DelayProfile', 'TDLC300', ...
            'NRxAnts', 4, ...
            'Format', 'A1', ...
            'SNR', -7.3 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 4', ...
            'DelayProfile', 'TDLC300', ...
            'NRxAnts', 4, ...
            'Format', 'A2', ...
            'SNR', -10.3 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 4', ...
            'DelayProfile', 'TDLC300', ...
            'NRxAnts', 4, ...
            'Format', 'A3', ...
            'SNR', -11.7 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 4', ...
            'DelayProfile', 'TDLC300', ...
            'NRxAnts', 4, ...
            'Format', 'B4', ...
            'SNR', -13.8 ...
        ), ...
        ... struct( ...
        ...     'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 4', ...
        ...     'DelayProfile', 'TDLC300', ...
        ...     'NRxAnts', 4, ...
        ...     'Format', 'C0', ...
        ...     'SNR', -4.3 ...
        ... ), ...
        ... struct( ...
        ...     'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-2 Row 4', ...
        ...     'DelayProfile', 'TDLC300', ...
        ...     'NRxAnts', 4, ...
        ...     'Format', 'C2', ...
        ...     'SNR', -10.2 ...
        ... ), ...
        ... Short PRACH 30 kHz
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 1', ...
            'DelayProfile', 'AWGN', ...
            'NRxAnts', 2, ...
            'Format', 'A1', ...
            'SNR', -9.1 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 1', ...
            'DelayProfile', 'AWGN', ...
            'NRxAnts', 2, ...
            'Format', 'A2', ...
            'SNR', -12.0 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 1', ...
            'DelayProfile', 'AWGN', ...
            'NRxAnts', 2, ...
            'Format', 'A3', ...
            'SNR', -13.8 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 1', ...
            'DelayProfile', 'AWGN', ...
            'NRxAnts', 2, ...
            'Format', 'B4', ...
            'SNR', -16.5 ...
        ), ...
        ... struct( ...
        ...     'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 1', ...
        ...     'DelayProfile', 'AWGN', ...
        ...     'NRxAnts', 2, ...
        ...     'Format', 'C0', ...
        ...     'SNR', -6.1 ...
        ... ), ...
        ... struct( ...
        ...     'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 1', ...
        ...     'DelayProfile', 'AWGN', ...
        ...     'NRxAnts', 2, ...
        ...     'Format', 'C2', ...
        ...     'SNR', -11.9 ...
        ... ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 2', ...
            'DelayProfile', 'TDLC300', ...
            'NRxAnts', 2, ...
            'Format', 'A1', ...
            'SNR', -2.8 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 2', ...
            'DelayProfile', 'TDLC300', ...
            'NRxAnts', 2, ...
            'Format', 'A2', ...
            'SNR', -5.7 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 2', ...
            'DelayProfile', 'TDLC300', ...
            'NRxAnts', 2, ...
            'Format', 'A3', ...
            'SNR', -7.4 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 2', ...
            'DelayProfile', 'TDLC300', ...
            'NRxAnts', 2, ...
            'Format', 'B4', ...
            'SNR', -9.9 ...
        ), ...
        ... struct( ...
        ...     'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 2', ...
        ...     'DelayProfile', 'TDLC300', ...
        ...     'NRxAnts', 2, ...
        ...     'Format', 'C0', ...
        ...     'SNR', 0.1 ...
        ... ), ...
        ... struct( ...
        ...     'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 2', ...
        ...     'DelayProfile', 'TDLC300', ...
        ...     'NRxAnts', 2, ...
        ...     'Format', 'C2', ...
        ...     'SNR', -5.6 ...
        ... ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 3', ...
            'DelayProfile', 'AWGN', ...
            'NRxAnts', 4, ...
            'Format', 'A1', ...
            'SNR', -11.4 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 3', ...
            'DelayProfile', 'AWGN', ...
            'NRxAnts', 4, ...
            'Format', 'A2', ...
            'SNR', -14.2 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 3', ...
            'DelayProfile', 'AWGN', ...
            'NRxAnts', 4, ...
            'Format', 'A3', ...
            'SNR', -15.9 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 3', ...
            'DelayProfile', 'AWGN', ...
            'NRxAnts', 4, ...
            'Format', 'B4', ...
            'SNR', -19.0 ...
        ), ...
        ... struct( ...
        ...     'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 3', ...
        ...     'DelayProfile', 'AWGN', ...
        ...     'NRxAnts', 4, ...
        ...     'Format', 'C0', ...
        ...     'SNR', -8.6 ...
        ... ), ...
        ... struct( ...
        ...     'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 3', ...
        ...     'DelayProfile', 'AWGN', ...
        ...     'NRxAnts', 4, ...
        ...     'Format', 'C2', ...
        ...     'SNR', -14.1 ...
        ... ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 4', ...
            'DelayProfile', 'TDLC300', ...
            'NRxAnts', 4, ...
            'Format', 'A1', ...
            'SNR', -7.2 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 4', ...
            'DelayProfile', 'TDLC300', ...
            'NRxAnts', 4, ...
            'Format', 'A2', ...
            'SNR', -10.4 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 4', ...
            'DelayProfile', 'TDLC300', ...
            'NRxAnts', 4, ...
            'Format', 'A3', ...
            'SNR', -12.0 ...
        ), ...
        struct( ...
            'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 4', ...
            'DelayProfile', 'TDLC300', ...
            'NRxAnts', 4, ...
            'Format', 'B4', ...
            'SNR', -14.5 ...
        ), ...
        ... struct( ...
        ...     'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 4', ...
        ...     'DelayProfile', 'TDLC300', ...
        ...     'NRxAnts', 4, ...
        ...     'Format', 'C0', ...
        ...     'SNR', -4.5 ...
        ... ), ...
        ... struct( ...
        ...     'Name', 'TS38.104 V15.19.0 Table 8.4.2.2-3 Row 4', ...
        ...     'DelayProfile', 'TDLC300', ...
        ...     'NRxAnts', 4, ...
        ...     'Format', 'C2', ...
        ...     'SNR', -10.4 ...
        ... ) ...
    };
end % of function createTestConfig()
