%CheckPUSCHConformance Battery of conformance tests for the PUSCH.
%   This class, based on the matlab.unittest.TestCase framework, performs a battery
%   of conformance tests on the PUSCH. Specifically, the tests are a subset of
%   those described in TS38.104 Section 8.2 and TS38.141 Section 8.2, plus some
%   custom tests. The tests consist in running a short simulation and ensuring
%   that the estimated throughput is above the required value.
%
%   CheckPUSCHConformance Properties (Constant):
%
%   FRC  - Fixed Reference Channels.
%
%   CheckPUSCHConformance Properties (TestParameter):
%
%   TestConfig  - PUSCH test configuration.
%
%   CheckPUSCHConformance Methods (Test, TestTags = {'conformance'}):
%
%   checkPUSCHconformance  - Verifies that the target throughput is achieved for
%                            the given PUSCH configuration.
%
%   Example
%      runtests('CheckPUSCHConformance')
%
%   See also matlab.unittest, PUSCHBLER.

%   Copyright 2021-2024 Software Radio Systems Limited
%
%   This file is part of srsRAN-matlab.
%
%   srsRAN-matlab is free software: you can redistribute it and/or
%   modify it under the terms of the BSD 2-Clause License.
%
%   srsRAN-matlab is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
%   BSD 2-Clause License for more details.
%
%   A copy of the BSD 2-Clause License can be found in the LICENSE
%   file in the top-level directory of this distribution.

classdef CheckPUSCHConformance < matlab.unittest.TestCase
    properties (Constant)
        %Fixed Reference Channels.
        %   Dictionary of parameters of the reference measurement channels. Keys
        %   parameters are taken from TS38.104 Appendix A.
        FRC = createFRC()
    end % of properties (Constant)

    properties (TestParameter)
        %PUSCH test configurations.
        %   Defines, for each test, the DelayProfile, the DelaySpread and the
        %   MaximumDopplerShift of the channel, the number of Rx antennas NRxAnts,
        %   the FRC and the target SNR.
        TestConfig = createTestConfig()
    end % of properties (TestParameter)

    methods (Test, TestTags = {'conformance'})
        function checkPUSCHconformance(obj, TestConfig)
        %Verifies that the target throughput is achieved for the given PUSCH configuration.
        %   Tests are limited to PUSCH configurations with transform precoding disabled and
        %   without multiplexed UCI bits.

            import matlab.unittest.fixtures.CurrentFolderFixture
            import matlab.unittest.constraints.IsFile

            obj.applyFixture(CurrentFolderFixture('../apps/simulators/PUSCHBLER'));

            try
                pp = PUSCHBLER;
            catch ME
                obj.assertFail(['Could not create a PUSCHBLER object because of exception: ', ...
                    ME.message]);
            end

            obj.assertClass(pp, 'PUSCHBLER', 'The created object is not a PUSCHBLER object.');

            obj.assertThat('../../../+srsMEX/+phy/@srsPUSCHDecoder/pusch_decoder_mex.mexa64', IsFile, ...
                'Could not find PUSCH decoder mex executable.');
            obj.assertThat('../../../+srsMEX/+phy/@srsPUSCHDemodulator/pusch_demodulator_mex.mexa64', IsFile, ...
                'Could not find PUSCH demodulator mex executable.');
            obj.assertThat('../../../+srsMEX/+phy/@srsMultiPortChannelEstimator/multiport_channel_estimator_mex.mexa64', IsFile, ...
                'Could not find channel estimator mex executable.');

            % Avoid meaningless warnings.
            puschblerwarn = warning('query', 'MATLAB:system:nonRelevantProperty');
            warning('off', 'MATLAB:system:nonRelevantProperty');

            % Simulation set-up.
            frc = obj.FRC(TestConfig.FRC);
            pp.SubcarrierSpacing = frc.SubcarrierSpacing;
            if contains(TestConfig.Name, 'Custom')
                pp.NSizeGrid = 273;
            else
                pp.NSizeGrid = frc.PRBSet(end) + 1;
            end
            pp.PRBSet = frc.PRBSet;
            pp.MCSTable = 'custom';
            pp.Modulation = frc.Modulation;
            pp.TargetCodeRate = frc.TargetCodeRate;
            pp.NRxAnts = TestConfig.NRxAnts;
            pp.DelayProfile = TestConfig.DelayProfile;
            pp.DelaySpread = TestConfig.DelaySpread;
            pp.MaximumDopplerShift = TestConfig.MaximumDopplerShift;
            pp.PerfectChannelEstimator = false;
            pp.EnableHARQ = true;
            pp.ImplementationType = 'srs';
            pp.SRSEstimatorType = 'MEX';
            pp.QuickSimulation = false;

            % Restore warnings.
            warning(puschblerwarn);

            mu = frc.SubcarrierSpacing / 15 - 1;
            nFrames = 400 / 2^mu;
            try
                pp(TestConfig.SNR, nFrames);
            catch ME
                obj.assertFail(['PUSCHBLER simulation failed with error: ', ME.message]);
            end

            tp = pp.ThroughputSRS / pp.MaxThroughput;

            if contains(TestConfig.Name, 'Custom')
                obj.verifyEqual(tp, 1.0, 'Throughput should be maximum for ''Custom'' cases.', AbsTol=1e-8);
                obj.assertGreaterThan(tp, 0.98, 'Throughput should be maximum for ''Custom'' cases.');
            else
                obj.verifyGreaterThanOrEqual(tp, 0.75, 'Throughput should be at least 70% for TS cases.');
                obj.assertGreaterThan(tp, 0.70, 'Throughput should be at least 70% for TS cases.');
            end

            % TODO: export throughput (and possibly other metrics) to grafana.

        end % of function checkPUSCHconformance(obj, TestConfig)
    end % of methods (Test, TestTags = {'conformance'})
end % of classdef CheckConformance < matlab.unittest.TestCase

function frcdictionary = createFRC()
    frcdictionary = dictionary( ...
... Table A.3-2: FRC parameters for FR1 PUSCH performance requirements,
... transform precoding disabled, Additional DM-RS position = pos1 and
... one transmission layer (QPSK, R=193/1024).
        'G-FR1-A3-8',  struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:24, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-9',  struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:51, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-10', struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:105, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-11', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:23, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-12', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:50, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-13', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:105, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
        'G-FR1-A3-14', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:272, ...
                              'TargetCodeRate',    193/1024, ...
                              'Modulation',        'QPSK'), ...
... Table A.4-2: FRC parameters for FR1 PUSCH performance requirements,
... transform precoding disabled, Additional DM-RS position = pos1 and
... one transmission layer (16QAM, R=658/1024).
        'G-FR1-A4-8',  struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:24, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A4-9',  struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:51, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A4-10', struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:105, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A4-11', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:23, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A4-12', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:50, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A4-13', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:105, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
        'G-FR1-A4-14', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:272, ...
                              'TargetCodeRate',    658/1024, ...
                              'Modulation',        '16QAM'), ...
... Table A.5-2: FRC parameters for FR1 PUSCH performance requirements,
... transform precoding disabled, Additional DM-RS position = pos1 and
... one transmission layer (64QAM, R=567/1024)
        'G-FR1-A5-8',  struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:24, ...
                              'TargetCodeRate',    567/1024, ...
                              'Modulation',        '64QAM'), ...
        'G-FR1-A5-9',  struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:51, ...
                              'TargetCodeRate',    567/1024, ...
                              'Modulation',        '64QAM'), ...
        'G-FR1-A5-10', struct('SubcarrierSpacing', 15, ...
                              'PRBSet',            0:105, ...
                              'TargetCodeRate',    567/1024, ...
                              'Modulation',        '64QAM'), ...
        'G-FR1-A5-11', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:24, ...
                              'TargetCodeRate',    567/1024, ...
                              'Modulation',        '64QAM'), ...
        'G-FR1-A5-12', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:50, ...
                              'TargetCodeRate',    567/1024, ...
                              'Modulation',        '64QAM'), ...
        'G-FR1-A5-13', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:105, ...
                              'TargetCodeRate',    567/1024, ...
                              'Modulation',        '64QAM'), ...
        'G-FR1-A5-14', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:272, ...
                              'TargetCodeRate',    567/1024, ...
                              'Modulation',        '64QAM'), ...
... Custom FRC configurations.
        'Custom-Max-1PRB', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0, ...
                              'TargetCodeRate',    772/1024, ...
                              'Modulation',        '256QAM'), ...
        'Custom-Max-2PRB', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:1, ...
                              'TargetCodeRate',    772/1024, ...
                              'Modulation',        '256QAM'), ...
        'Custom-Max-4PRB', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:3, ...
                              'TargetCodeRate',    772/1024, ...
                              'Modulation',        '256QAM'), ...
        'Custom-Max-8PRB', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:7, ...
                              'TargetCodeRate',    772/1024, ...
                              'Modulation',        '256QAM'), ...
        'Custom-Max-15PRB', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:14, ...
                              'TargetCodeRate',    772/1024, ...
                              'Modulation',        '256QAM'), ...
        'Custom-Max-10MHz', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:24, ...
                              'TargetCodeRate',    772/1024, ...
                              'Modulation',        '256QAM'), ...
        'Custom-Max-20MHz', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:50, ...
                              'TargetCodeRate',    772/1024, ...
                              'Modulation',        '256QAM'), ...
        'Custom-Max-40MHz', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:105, ...
                              'TargetCodeRate',    772/1024, ...
                              'Modulation',        '256QAM'), ...
        'Custom-Max-100MHz', struct('SubcarrierSpacing', 30, ...
                              'PRBSet',            0:272, ...
                              'TargetCodeRate',    772/1024, ...
                              'Modulation',        '256QAM') ...
    );
end % of function frcdictionary = createFRC()

function TestConfig = createTestConfig()
    TestConfig = { ...
... PUSCH, Type A, 10 MHz channel bandwidth, 30 kHz SCS.
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-4 Row 1', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A3-11', ...
            'SNR',                 -2.3 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-4 Row 2', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A4-11', ...
            'SNR',                 10.2 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-4 Row 3', ...
            'DelayProfile',        'TDLA30', ...
            'MaximumDopplerShift', 10, ...
            'DelaySpread',         0, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A5-11', ...
            'SNR',                 12.8 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-4 Row 4', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A3-11', ...
            'SNR',                 -5.6 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-4 Row 5', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A4-11', ...
            'SNR',                 6.4 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-4 Row 6', ...
            'DelayProfile',        'TDLA30', ...
            'MaximumDopplerShift', 10, ...
            'DelaySpread',         0, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A5-11', ...
            'SNR',                 8.6 ...
        ), ...
... PUSCH, Type A, 20 MHz channel bandwidth, 30 kHz SCS.
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-5 Row 1', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A3-12', ...
            'SNR',                 -2.9 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-5 Row 2', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A4-12', ...
            'SNR',                 10.2 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-5 Row 3', ...
            'DelayProfile',        'TDLA30', ...
            'MaximumDopplerShift', 10, ...
            'DelaySpread',         0, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A5-12', ...
            'SNR',                 12.5 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-5 Row 4', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A3-12', ...
            'SNR',                 -6.0 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-5 Row 5', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A4-12', ...
            'SNR',                 6.4 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-5 Row 6', ...
            'DelayProfile',        'TDLA30', ...
            'MaximumDopplerShift', 10, ...
            'DelaySpread',         0, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A5-12', ...
            'SNR',                 8.6 ...
        ), ...
... PUSCH, Type A, 40 MHz channel bandwidth, 30 kHz SCS.
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-6 Row 1', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A3-13', ...
            'SNR',                 -2.5 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-6 Row 2', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A4-13', ...
            'SNR',                 10 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-6 Row 3', ...
            'DelayProfile',        'TDLA30', ...
            'MaximumDopplerShift', 10, ...
            'DelaySpread',         0, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A5-13', ...
            'SNR',                 12.4 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-6 Row 4', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A3-13', ...
            'SNR',                 -5.8 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-6 Row 5', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A4-13', ...
            'SNR',                 6.3 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-6 Row 6', ...
            'DelayProfile',        'TDLA30', ...
            'MaximumDopplerShift', 10, ...
            'DelaySpread',         0, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A5-13', ...
            'SNR',                 8.5 ...
        ), ...
... PUSCH, Type A, 100 MHz channel bandwidth, 30 kHz SCS.
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-7 Row 1', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A3-14', ...
            'SNR',                 -2.8 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-7 Row 2', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A4-14', ...
            'SNR',                 10.2 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-7 Row 3', ...
            'DelayProfile',        'TDLA30', ...
            'MaximumDopplerShift', 10, ...
            'DelaySpread',         0, ...
            'NRxAnts',             2, ...
            'FRC',                 'G-FR1-A5-14', ...
            'SNR',                 13 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-7 Row 4', ...
            'DelayProfile',        'TDLB100', ...
            'MaximumDopplerShift', 400, ...
            'DelaySpread',         0, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A3-14', ...
            'SNR',                 -5.8 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-7 Row 5', ...
            'DelayProfile',        'TDLC300', ...
            'MaximumDopplerShift', 100, ...
            'DelaySpread',         0, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A4-14', ...
            'SNR',                 6.5 ...
        ), ...
        struct( ...
            'Name',                'TS38.104 V15.19.0 Table 8.2.1.2-7 Row 6', ...
            'DelayProfile',        'TDLA30', ...
            'MaximumDopplerShift', 10, ...
            'DelaySpread',         0, ...
            'NRxAnts',             4, ...
            'FRC',                 'G-FR1-A5-14', ...
            'SNR',                 9 ...
        ), ...
... Custom test cases with perfect channel.
        struct( ...
            'Name',                'Custom Max 1PRB', ...
            'DelayProfile',        'single-tap', ...
            'DelaySpread',         2.0e-7, ...
            'MaximumDopplerShift', 0, ...
            'NRxAnts',             1, ...
            'FRC',                 'Custom-Max-1PRB', ...
            'SNR',                 60 ...
        ), ...
        struct( ...
            'Name',                'Custom Max 2PRB', ...
            'DelayProfile',        'single-tap', ...
            'DelaySpread',         2.0e-7, ...
            'MaximumDopplerShift', 0, ...
            'NRxAnts',             1, ...
            'FRC',                 'Custom-Max-2PRB', ...
            'SNR',                 60 ...
        ), ...
        struct( ...
            'Name',                'Custom Max 4PRB', ...
            'DelayProfile',        'single-tap', ...
            'DelaySpread',         2.0e-7, ...
            'MaximumDopplerShift', 0, ...
            'NRxAnts',             1, ...
            'FRC',                 'Custom-Max-4PRB', ...
            'SNR',                 60 ...
        ), ...
        struct( ...
            'Name',                'Custom Max 8PRB', ...
            'DelayProfile',        'single-tap', ...
            'DelaySpread',         2.0e-7, ...
            'MaximumDopplerShift', 0, ...
            'NRxAnts',             1, ...
            'FRC',                 'Custom-Max-8PRB', ...
            'SNR',                 60 ...
        ), ...
        struct( ...
            'Name',                'Custom Max 15PRB', ...
            'DelayProfile',        'single-tap', ...
            'DelaySpread',         2.0e-7, ...
            'MaximumDopplerShift', 0, ...
            'NRxAnts',             1, ...
            'FRC',                 'Custom-Max-15PRB', ...
            'SNR',                 60 ...
        ), ...
        struct( ...
            'Name',                'Custom Max 10MHz', ...
            'DelayProfile',        'single-tap', ...
            'DelaySpread',         2.0e-7, ...
            'MaximumDopplerShift', 0, ...
            'NRxAnts',             1, ...
            'FRC',                 'Custom-Max-10MHz', ...
            'SNR',                 60 ...
        ), ...
        struct( ...
            'Name',                'Custom Max 20MHz', ...
            'DelayProfile',        'single-tap', ...
            'DelaySpread',         2.0e-7, ...
            'MaximumDopplerShift', 0, ...
            'NRxAnts',             1, ...
            'FRC',                 'Custom-Max-20MHz', ...
            'SNR',                 60 ...
        ), ...
        struct( ...
            'Name',                'Custom Max 40MHz', ...
            'DelayProfile',        'single-tap', ...
            'DelaySpread',         2.0e-7, ...
            'MaximumDopplerShift', 0, ...
            'NRxAnts',             1, ...
            'FRC',                 'Custom-Max-40MHz', ...
            'SNR',                 60 ...
        ), ...
        struct( ...
            'Name',                'Custom Max 100MHz', ...
            'DelayProfile',        'single-tap', ...
            'DelaySpread',         2.0e-7, ...
            'MaximumDopplerShift', 0, ...
            'NRxAnts',             1, ...
            'FRC',                 'Custom-Max-100MHz', ...
            'SNR',                 60 ...
        ) ...
    };
end % of function TestConfig = createTestConfig()
